server:
  port: 8888
#  servlet:
#    context-path: /sb
spring:
  datasource:
    url: jdbc:mysql://172.24.131.57:40155/smartdb?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&autoReconnectForPools=true&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: smartbuilding
mybatis:
  type-aliases-package: com.bz
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml

car:
  monitor:
    history: http://39.108.247.181:8083/back/cd/historyData
    warning: http://39.108.247.181:8083/back/cd/warningData
    info: http://39.108.247.181:8083/back/cd/info
    realtime: http://39.108.247.181:8083/back/cd/realtimeData

zhatubao:
  username: gxenv
  appkey: r42ee45t
  appsecret: 1w233e4rsd54tf5t
  getAuthTokenUrl: http://ticketapitest.shomes.cn/api/data/getAuthToken
  getVehicleInfoUrl: http://ticketapitest.shomes.cn/api/data/getVehicleInfo
  getVehicleStatusurl: http://ticketapitest.shomes.cn/api/data/getVehicleStatus

huazhi:
  corpid: ww49756ef28b994063
  corpsecret: cBhyIa6LwLbt3wMZAy_JHTQLf1nBlQ1PLDbl5KKfgVM
  authTokenUrl: http://39.100.155.16:9008/auth/gettoken
  environmentalAirDataUrl: http://39.100.155.16:9008/environment-monitoring-data-api/v1/air/list