spring:
  profiles:
    active: dev
  #boot返回前台时间默认使用GMT，相差8小时
  jackson:
    time-zone: GMT+8
#聚光大气数据
jg:
  air-data:
    userName: chengdu
    password: 924713836750bf25ab10b409682bccd0
    stationCodes: CEG420B0066*,CEG420B0069*,CEG420B0008*
    dataMinUrl: http://119.3.48.160/agms-prj-server/api/v1/web/outside/site-real-data
    dataHourUrl: http://119.3.48.160/agms-prj-server/api/v1/web/outside/get-site-hours-data
    datasHourUrl: http://119.3.48.160/agms-prj-server/api/v1/web/outside/get-site-hours-data-time
# 成都市控站大气
chengdu:
  airdata:
    url: http://118.116.8.14:8080/apigateway/data/publish/DefaultHandler?action=GetRealTimeData&_=