server:
  port: 8888
#  servlet:
#    context-path: /sb
spring:
  datasource:
    url: jdbc:mysql://172.24.131.57:40155/smartdb?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&autoReconnectForPools=true&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: smartbuilding
mybatis:
  type-aliases-package: com.bz
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml

car:
  monitor:
    history: http://39.108.247.181:8083/back/cd/historyData
    warning: http://39.108.247.181:8083/back/cd/warningData
    info: http://39.108.247.181:8083/back/cd/info
    realtime: http://39.108.247.181:8083/back/cd/realtimeData

zhatubao:
  username: gaoxin
  appkey: tr67y8uu
  appsecret: wdr43ee5y7u44ffg
  getAuthTokenUrl: http://ticketapi.shomes.cn/api/data/getAuthToken
  getVehicleInfoUrl: http://ticketapi.shomes.cn/api/data/getVehicleInfo
  getVehicleStatusurl: http://ticketapi.shomes.cn/api/data/getVehicleStatus
  getVehicleRecentPic: http://ticketapi.shomes.cn/api/data/getVehicleRecentPic
  vehicleRecentGps: http://ticketapi.shomes.cn/api/data/getVehicleRecentGps

huazhi:
  corpid: ww49756ef28b994063
  corpsecret: cBhyIa6LwLbt3wMZAy_JHTQLf1nBlQ1PLDbl5KKfgVM
  authTokenUrl: http://39.100.155.16:9008/auth/gettoken
  environmentalAirDataUrl: https://dzgtest.palmte.cn/smartws/api/v1/epdata
  weather:
    pm10Limit: 40
  warning:
    grant_type: client_credentials
    client_id: user123
    client_secret: 123456
    user: usercode:admin
    warningType: 1,2,35,63
    warningTokenUrl: http://222.209.208.170:11125/sso/oauth2.0/accessToken
    warningDataUrl: http://222.209.208.170:11125/api/uss/v1/ams/record/alarm/page
#金时利LED
#KIMSHL:
#  netProtocal: 1
#  typeNo: 41
#  frontBody: 1
#  frontSize: 1
#  frontColor: 1
#  cardIp: 192.168.2.239

#金时利
jinshili:
  carInfo: http://172.24.131.57:18082/park/exitAndEntry
  barrierGateInfo: http://172.24.131.57:18082/park/gateInfo
